/* (c) https://github.com/MontiCore/monticore */
plugins {
  id 'java-library'
  id 'java-gradle-plugin'
  id 'maven-publish'
}

dependencies {
  implementation "de.se_rwth.commons:se-commons-gradle:$mc_version"
  compileOnly project(":")
  testImplementation "org.junit.jupiter:junit-jupiter-api:$junit_jupiter_version"
  testImplementation "org.junit.jupiter:junit-jupiter-params:$junit_jupiter_version"
  testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:$junit_jupiter_version"
  testRuntimeOnly "org.junit.platform:junit-platform-launcher:$junit_jupiter_version"
}

gradlePlugin {
  plugins {
    montifunPlugin {
      id = 'de.monticore.montifun'
      implementationClass = 'de.monticore.mf.montifun.gradleplugin.MontiFunGradlePlugin'
    }
  }
}

tasks.register('writeMCBuildInfo', de.monticore.gradle.common.MCBuildInfoTask.class) {
  getVersion().set(project.provider(() -> project.getVersion().toString()))
}
processResources {
  dependsOn tasks.named('writeMCBuildInfo')
}

tasks.withType(Test).configureEach {
  useJUnitPlatform()
}
