# (c) https://github.com/MontiCore/monticore

# Build JAVA applications using Apache Maven (http://maven.apache.org)

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository/
  key: "$CI_COMMIT_SHA" # Cache across branch and stage

stages:
  - build
  - test

Validate Gradle:
  image: registry.git.rwth-aachen.de/monticore/container-registry/gradle:6.8.2-jdk11
  stage: build
  script:
    - gradle clean assemble
  artifacts:
    paths:
      - ./target/
    expire_in: 1 week

Unit Test Gradle:
  image: registry.git.rwth-aachen.de/monticore/container-registry/gradle:6.8.2-jdk11
  stage: test
  needs: ["Validate Gradle"]
  dependencies:
    - Validate Gradle #download artifacts from build
  script:
    - gradle test

Deploy Nexus:
  image: registry.git.rwth-aachen.de/monticore/container-registry/gradle:6.8.2-jdk11
  stage: post-test
  needs: ["Validate Gradle"]
  dependencies:
    - Validate Gradle
  only:
    - dev
  script:
    - gradle publish -PmavenPassword=$pass -PmavenUser=$user
