/* (c) https://github.com/MontiCore/monticore */

plugins {
    id "java"
    id "de.monticore.generator" version "$mc_version"
    id "maven-publish"
    id "com.github.johnrengelman.shadow" version "$shadow_version"
}

description = "functional programming language"
buildDir = file("$projectDir/target")


def grammarDir = "$projectDir/src/main/grammars"
def grammarOutDir = "$buildDir/generated-sources/mc"
def testGrammarOutDir = "$buildDir/generated-test-sources/mc"
def reportsDir = "$buildDir/generated-sources/monticore/sourcecode/reports"

// configure non-standard source sets
sourceSets {
    main {
        java.srcDirs += ["$grammarOutDir"]
    }
    test {
        java.srcDirs += ["$testGrammarOutDir"]
    }
    grammars {
        resources {
            srcDirs(grammarDir)
            include "**/*.mc4"
        }
    }
}

configurations { grammar }

dependencies {
    grammar("de.monticore:monticore-grammar:$mc_version")
    grammar("de.monticore.lang:ocl:$mc_version")
    implementation "de.monticore:monticore-runtime:$mc_version"
    implementation "de.monticore:monticore-grammar:$mc_version"
    implementation "de.monticore:class2mc:$mc_version"
    implementation "de.se_rwth.commons:se-commons-logging:$mc_version"
    implementation group: 'org.antlr', name: 'antlr4-runtime', version: antlr_version
    implementation group: 'de.monticore.lang', name: 'cd4analysis', version: mc_version
    implementation group: 'de.monticore.lang', name: 'ocl', version: mc_version
    implementation "commons-cli:commons-cli:$commons_cli_version"
    implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.11'
    implementation group: 'commons-io', name: 'commons-io', version: '2.8.0'
    implementation "ch.qos.logback:logback-classic:$logback_version"
    testImplementation "junit:junit:$junit_version"
    testImplementation "org.junit.jupiter:junit-jupiter-api:$junit_jupiter_version"
    testImplementation "org.junit.jupiter:junit-jupiter-params:$junit_jupiter_version"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:$junit_jupiter_version"
    testImplementation "de.monticore:monticore-runtime:$mc_version"
}

repositories {
    if (("true").equals(getProperty('useLocalRepo'))) {
        mavenLocal()
    }
    maven {
        credentials.username mavenUser
        credentials.password mavenPassword
        url sePublicRepo
    }
    mavenCentral()
}

generateMCGrammars {
  // with Interpreter
  genINT = true
}

// Fixes issue with java plugin in projects without resources
compileTestJava.doFirst { mkdir sourceSets.main.output.resourcesDir }

tasks.withType(Test) {
    maxParallelForks = Runtime.runtime.availableProcessors() ?: 1
}

tasks.withType(JavaCompile) {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
    options.fork = true
    options.encoding = "UTF-8"
    options.deprecation false
    options.warnings = false
    options.headerOutputDirectory.convention(null)
}

// all in one cli-jar
shadowJar {
    manifest {
        attributes "Main-Class": "de.monticore.mf.montifun.MontiFunTool"
    }
    archiveFileName = "MCMontiFun.${archiveExtension.get()}"
    archiveClassifier = "mc-tool"
    minimize {
        //todo https://git.rwth-aachen.de/monticore/monticore/-/issues/3317
        exclude(dependency('org.freemarker:freemarker:.*'))
    }
}

test {
    useJUnitPlatform()
    //finalizedBy jacocoTestReport
}

task testReport(type: TestReport) {
    destinationDir = file("$buildDir/reports/allTests")
    // Include the results from the 'test' task
    reportOn tasks.withType(Test)
}

java {
//  withJavadocJar()
    withSourcesJar()
    registerFeature('grammars') {
        usingSourceSet(sourceSets.grammars)
    }
}

jar.dependsOn grammarsJar, shadowJar

// configure deployment
publishing {
    // configure what artifacts to publish
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
    repositories.maven {
	    name = "$SE_Nexus_ID"
        credentials.username mavenUser
        credentials.password mavenPassword
        def releasesRepoUrl = "https://nexus.se.rwth-aachen.de/content/repositories/monticore-releases/"
        def snapshotsRepoUrl = "https://nexus.se.rwth-aachen.de/content/repositories/monticore-snapshots/"
        url = version.endsWith("SNAPSHOT") ? snapshotsRepoUrl : releasesRepoUrl
    }
}

task buildAll(type: GradleBuild) {
    tasks = ['build']
}

defaultTasks('build')
