/* (c) https://github.com/MontiCore/monticore */
import org.gradle.api.tasks.testing.logging.TestExceptionFormat
import org.gradle.api.tasks.testing.logging.TestLogEvent

plugins {
  id "java"
  id "de.monticore.generator" version "$mc_version"
  id "maven-publish"
  id "com.gradleup.shadow" version "$shadow_version"
}

description = "functional programming language"

apply from: 'gradle-scripts/buildIntoTarget.gradle'
apply from: 'gradle-scripts/repositories.gradle'
apply from: 'gradle-scripts/configureMavenPublish.gradle'


dependencies {
  grammar("de.monticore.lang:ocl:$mc_version")
  implementation "de.monticore:class2mc:$mc_version"
  implementation "de.monticore.lang:cd4analysis:$mc_version"

  testImplementation "org.junit.jupiter:junit-jupiter-api:$junit_jupiter_version"
  testImplementation "org.junit.jupiter:junit-jupiter-params:$junit_jupiter_version"
  testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:$junit_jupiter_version"
  testRuntimeOnly "org.junit.platform:junit-platform-launcher:$junit_jupiter_version"
  testImplementation "de.monticore:monticore-runtime:$mc_version"
  testImplementation "de.monticore:javagen-runtime:$mc_version"
}

// Fixes issue with java plugin in projects without resources
compileTestJava.doFirst { mkdir sourceSets.main.output.resourcesDir }

tasks.withType(Test).configureEach {
  maxParallelForks = Runtime.runtime.availableProcessors() ?: 1
}

tasks.withType(JavaCompile).configureEach {
  sourceCompatibility = JavaVersion.VERSION_21
  targetCompatibility = JavaVersion.VERSION_21
  options.fork = true
  options.encoding = "UTF-8"
  options.deprecation = true
  options.warnings = true
  options.headerOutputDirectory.convention(null)
}

// all in one cli-jar
shadowJar {
  manifest {
    attributes "Main-Class": "de.monticore.mf.montifun.MontiFunTool"
  }
  archiveFileName = "MCMontiFun.${archiveExtension.get()}"
  archiveClassifier = "mc-tool"
  minimize {
    //todo https://git.rwth-aachen.de/monticore/monticore/-/issues/3317
    exclude(dependency('org.freemarker:freemarker:.*'))
  }
}

test {
  useJUnitPlatform()
  testLogging {
    // controls whether test output is shown
    showExceptions = true
    showCauses = true
    showStackTraces = true
    exceptionFormat = TestExceptionFormat.FULL
    info {
      events TestLogEvent.FAILED,
          TestLogEvent.PASSED,
          TestLogEvent.SKIPPED,
          TestLogEvent.STANDARD_OUT
    }
  }
}

tasks.register('testReport', TestReport) {
  destinationDirectory = layout.buildDirectory.dir("reports/allTests")
  // Include the results from the 'test' task
  getTestResults().from(tasks.withType(Test))
}

java {
  withJavadocJar()
  withSourcesJar()
}

jar.dependsOn shadowJar

publishing {
  publications {
    mavenJava(MavenPublication) {
      from components.java
    }
  }
}

tasks.register('buildAll', GradleBuild) {
  tasks = ['build']
}

defaultTasks('build')
