#repository related
mavenUser=${username}
mavenPassword=${password}
sePrivateRepo=https://nexus.se.rwth-aachen.de/content/groups/se/
sePublicRepo=https://nexus.se.rwth-aachen.de/content/groups/public
releasesRepoUrl=https://nexus.se.rwth-aachen.de/content/repositories/monticore-releases/
snapshotsRepoUrl=https://nexus.se.rwth-aachen.de/content/repositories/monticore-snapshots/
useLocalRepo=false

org.gradle.jvmargs=-Xmx2048m
org.gradle.vfs.watch=true
mc_version=7.10.0-SNAPSHOT
version=7.10.0-SNAPSHOT
group=de.monticore.lang
junit_jupiter_version=6.0.3
shadow_version=8.3.9
