#repository related
mavenUser=${username}
mavenPassword=${password}
sePrivateRepo=https://nexus.se.rwth-aachen.de/content/groups/se/
sePublicRepo=https://nexus.se.rwth-aachen.de/content/groups/public
releasesRepoUrl=https://nexus.se.rwth-aachen.de/content/repositories/monticore-releases/
snapshotsRepoUrl=https://nexus.se.rwth-aachen.de/content/repositories/monticore-snapshots/
SE_Nexus_ID=SE-nexus
useLocalRepo=false

org.gradle.jvmargs=-Xmx2048m
org.gradle.vfs.watch=true
mc_version=7.9.0-SNAPSHOT
version=7.9.0-SNAPSHOT
group=de.monticore.lang
commons_cli_version=1.11.0
commons_io_version=2.21.0
commons_lang3_version=3.20.0
antlr_version=4.13.2
guava_version=31.1-jre
logback_version=1.5.24
junit_version=4.13.2
junit_jupiter_version=5.9.1
shadow_version=8.3.9
