#repository related
mavenUser=${username}
mavenPassword=${password}
sePrivateRepo=https://nexus.se.rwth-aachen.de/content/groups/se/
sePublicRepo=https://nexus.se.rwth-aachen.de/content/groups/public
releasesRepoUrl=https://nexus.se.rwth-aachen.de/content/repositories/monticore-releases/
snapshotsRepoUrl=https://nexus.se.rwth-aachen.de/content/repositories/monticore-snapshots/
SE_Nexus_ID=SE-nexus
useLocalRepo=false

org.gradle.vfs.watch=true
mc_version=7.6.0
version=7.6.0
group=de.monticore.lang
commons_cli_version=1.5.0
antlr_version=4.12.0
guava_version=31.1-jre
logback_version=1.4.5
junit_version=4.13.2
junit_jupiter_version=5.9.1
shadow_version=6.1.0
