/* generated from model MontiFun */
/* generated by template cd2java.Class*/

/* (c) https://github.com/MontiCore/monticore */

/* Hookpoint: ClassContent:addComment */

/* generated by template cd2java.Package*/
package de.monticore.mf.montifun._symboltable;

import com.google.common.base.Preconditions;
import de.monticore.expressions.expressionsbasis._ast.ASTExpression;
import de.monticore.mf.montifun._ast.ASTMFConstantDeclaration;
import de.monticore.mf.montifun._ast.ASTMFFunctionDeclaration;
import de.monticore.symbols.basicsymbols._symboltable.FunctionSymbol;
import de.monticore.symbols.basicsymbols._symboltable.VariableSymbol;

public class MontiFunScopesGenitorDelegator
    extends MontiFunScopesGenitorDelegatorTOP {

  /**
   * Adds a function declaration to the enclosing scope.
   * This does not change the AST itself!
   *
   * @param node           The node that needs a symbol table
   * @param enclosingScope The enclosing scope
   * @return The symbol of the function declaration
   */
  public FunctionSymbol createFromAST(
      ASTMFFunctionDeclaration node,
      IMontiFunScope enclosingScope
  ) {
    Preconditions.checkNotNull(node);
    Preconditions.checkNotNull(enclosingScope);
    scopeStack.add(enclosingScope);
    try {
      node.accept(traverser);
    }
    finally {
      scopeStack.removeLast();
    }
    return node.getSymbol();
  }

  /**
   * Adds a constant declaration to the enclosing scope.
   * This does not change the AST itself!
   *
   * @param node           The node that needs a symbol table
   * @param enclosingScope The enclosing scope
   * @return The symbol of the constant declaration
   */
  public VariableSymbol createFromAST(
      ASTMFConstantDeclaration node,
      IMontiFunScope enclosingScope
  ) {
    Preconditions.checkNotNull(node);
    Preconditions.checkNotNull(enclosingScope);
    scopeStack.add(enclosingScope);
    try {
      node.accept(traverser);
    }
    finally {
      scopeStack.removeLast();
    }
    return node.getSymbol();
  }

  /**
   * Creates the symbol table of the Expression
   * with the given outer scope.
   *
   * @param node           The node that needs a symbol table
   * @param enclosingScope The enclosing scope
   */
  public void createFromAST(
      ASTExpression node,
      IMontiFunScope enclosingScope
  ) {
    Preconditions.checkNotNull(node);
    Preconditions.checkNotNull(enclosingScope);
    scopeStack.add(enclosingScope);
    try {
      node.accept(traverser);
    }
    finally {
      scopeStack.removeLast();
    }
  }

}


