/* (c) https://github.com/MontiCore/monticore */

plugins {
  id 'de.monticore.montifun' version "$version"
  id 'java'
}

dependencies {
  testImplementation "org.junit.jupiter:junit-jupiter-api:$junit_jupiter_version"
  testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:$junit_jupiter_version"
  testRuntimeOnly "org.junit.platform:junit-platform-launcher:$junit_jupiter_version"
}

test {
  useJUnitPlatform()
}
