/* (c) https://github.com/MontiCore/monticore */
pluginManagement {
  // get the plugin using include
  includeBuild('../../..')

  repositories {
    if (("true").equals(getProperty('useLocalRepo'))) {
      mavenLocal()
    }
    mavenCentral()
    gradlePluginPortal()

    maven {
      url "https://nexus.se.rwth-aachen.de/content/groups/public"
    }
  }
}
rootProject.name = 'montifun-gradle-plugin-it'
